server:
  port: 8088
  
spring:
  mvc:    view:      suffix: .html  datasource:    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password: 
    driver-class-name: org.h2.Driver
      jpa:    hibernate:      ddl-auto: create
      #use-new-id-generator-mappings: false
    properties:      hibernate:
        '[default_batch_fetch_size]': 100      
        '[format_sql]': true    open-in-view: false

logging:
  level:
    '[org.hibernate.SQL]': debug
    '[org.hibernate.type.descriptor.sql]': trace
#    파라미터 출력을 위한 외부 라이브러리 P6Spy    